mode: parallel
containers:
  - address: http://192.168.31.233:5700
    username: admin
    password: admin
    weigth:  
    mode: parallel
    limit: 9999
theme:  
static: ./static
master: 
database:  
qywx_key:
daily_push:
resident:
user_agent:
telegram_bot_token:
telegram_user_id:
qquid:
qqgid:
qbot_public_mode: true
default_priority:
no_ghproxy: true
daily_asset_push_cron: 5 20 * * *
task:
  - cron: 6 6 * * *
    path: https://raw.githubusercontent.com/cdle/xdd/main/scripts/jd_goodMorning.js
    enable: true
    word: 早起福利
    mode: obo
  - cron: 0 0 * * *
    path: https://raw.githubusercontent.com/cdle/xdd/main/scripts/jd_angryBean.js
    enable: true
    word: 抢京豆
    mode: alo
    env:
      - name: angryBeanPins
      - value: jd_xxxxx&jd_ooooo
repos:
  - git: https://github.com/shufflewzc/faker2.git
